### ISSUE TITLE
Combine posts not being accepted by crits

### ISSUE THREAD

**Issue by cjdupreez** [mlsecproject/combine#150]
Hi, I'm trying to get CRITS to accept the posts Combine is sending it, however CRITS is refusing to accept the POSTS. Here is a snippet of the traffic:

![image](https://cloud.githubusercontent.com/assets/5132774/9472365/e0413202-4b22-11e5-8b53-359c94d7a5d4.png)

Is this something I've not configured? I followed the step by step install instructions for both Crits and Combine.

Thanks in advance,
-Cornel.

**Comment by alexcpsec** [comment]
Hi, Cornell!

This is a known issue. Could you have a look at PR https://github.com/mlsecproject/combine/pull/148 and check if it does the trick for you? I have been struggling for time to merge it to master, sadly.

If I have a :+1: from you, I'll do my best to make it happen as soon as I can.

**Comment by cjdupreez** [comment]
Hi Alex, thanks for the quick response. Unfortunately PR #148 didn't do the trick for me. We did however figure out what the problem was and how to fix it. The problem is when Combine posts to CRITs, it's sending the ip_type variable as "Address - ipv4-addr". In the CRITs vocab file ips.py, CRITs is expecting "IPv4 Address". So by changing baler.py to send data['ip_type'] = 'IPv4 Address', CRITs accepts the POSTs.
