### ISSUE TITLE
from thresher import thresh

### ISSUE THREAD

**Issue by kozanostra2x2i** [mlsecproject/combine#158]
i start receiving this type error:
       kalaja@ubuntu:~/combine$ ./combine.py 
         Traceback (most recent call last):
         File "./combine.py", line 11, in <module>
         from thresher import thresh
          File "/home/kalaja/combine/thresher.py", line 2, in <module>
          import bs4
           ImportError: No module named bs4

even though i have these modules nad program ran fine until this morning, any suggestions please?
thanks a lot...

**Comment by kozanostra2x2i** [comment]
kalaja@ubuntu:~/combine$ sudo pip install bs4
[sudo] password for kalaja: 
Requirement already satisfied (use --upgrade to upgrade): bs4 in /usr/local/lib/python2.7/dist-packages
Cleaning up...

**Comment by kozanostra2x2i** [comment]
for some reason beutifulsoup4 was corrupted and i had to reinstalled with pip, which fixed the proplem with "ImportError: No module named bs4"
No im receiving:
TypeError: map() got an unexpected keyword argument 'exception_handler'

**Comment by kozanostra2x2i** [comment]
error:
"TypeError: map() got an unexpected keyword argument 'exception_handler'"
i have fixed by this command:
pip install git+https://github.com/kennethreitz/grequests.git

**Comment by alexcpsec** [comment]
Hey!

We usually suggest that people do a fresh venv container to help with any issues like that. We are still using a fork of gevents because of the exception handling. If you have some time, could you check if the fresh install option works?

```
sudo apt-get install python-dev python-pip python-virtualenv git
git clone https://github.com/mlsecproject/combine.git
cd combine
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
````

**Comment by kozanostra2x2i** [comment]
@alexcpsec thanks fro respond. I have fixed the issues and i have been very happy with results of combine.py. GREAT WORK!

**Comment by alexcpsec** [comment]
Thanks!
